[project]
name = "liontalk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "playwright>=1.57.0",
    "requests>=2.32.5",
]
